### ISSUE TITLE
No Data is found on vnstat v2.9

### ISSUE THREAD

**Issue by AliBasicCoder** [Hulxv/vnstat-client#7]
**Describe the bug**
the app doesn't work on my device vnstat v2.9
info:
```
> vnstat-client
(node:6408) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replace')
    at At.db (/opt/vnstat-client/resources/app.asar/app/background.js:1:52509)
    at Tt.init (/opt/vnstat-client/resources/app.asar/app/background.js:1:53548)
    at /opt/vnstat-client/resources/app.asar/app/background.js:1:54337
    at /opt/vnstat-client/resources/app.asar/app/background.js:1:63127
    at Object.<anonymous> (/opt/vnstat-client/resources/app.asar/app/background.js:1:63148)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
(Use `vnstat-client --trace-warnings ...` to show where the warning was created)
(node:6408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
16:56:36.577 › [PRODUCTION] vnStat Client is Running.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[6444:0226/165636.634266:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
16:56:37.208 › Getting data...
16:56:37.209 › TypeError: Cannot read properties of undefined (reading 'replace')
    at At.db (/opt/vnstat-client/resources/app.asar/app/background.js:1:52509)
    at Tt.init (/opt/vnstat-client/resources/app.asar/app/background.js:1:53548)
    at /opt/vnstat-client/resources/app.asar/app/background.js:1:54337
    at /opt/vnstat-client/resources/app.asar/app/background.js:1:63127
    at Object.<anonymous> (/opt/vnstat-client/resources/app.asar/app/background.js:1:63148)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
(node:6408) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:6408) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'replace')
    at At.db (/opt/vnstat-client/resources/app.asar/app/background.js:1:52509)
    at Tt.init (/opt/vnstat-client/resources/app.asar/app/background.js:1:53548)
    at /opt/vnstat-client/resources/app.asar/app/background.js:1:58865
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:6408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

```

```
> uname -a
Linux aliahmed-h310ms2v 5.15.21-1-MANJARO #1 SMP PREEMPT Sun Feb 6 12:21:42 UTC 2022 x86_64 GNU/Linux
```

```
> vnstat -v
vnStat 2.9 by Teemu Toivola <tst at iki dot fi>
```

```
> vnstat

                      rx      /      tx      /     total    /   estimated
 enp1s0:
       2022-02     10.06 GiB  /    7.94 GiB  /   18.00 GiB  /   19.60 GiB
     yesterday    942.62 MiB  /   45.25 MiB  /  987.87 MiB
         today     74.28 MiB  /    5.13 MiB  /   79.41 MiB  /  112.66 MiB

 wlp0s20f0u5:
       2022-02      8.47 GiB  /    3.84 GiB  /   12.31 GiB  /   13.41 GiB
     yesterday           0 B  /         0 B  /         0 B
         today           0 B  /         0 B  /         0 B  /     --     
```

**To Reproduce**
open app
Note when i click on Refresh button this appers
```
16:57:40.452 › Getting data...
16:57:40.453 › Cannot read properties of undefined (reading 'replace')
16:57:40.454 › TypeError: Cannot read properties of undefined (reading 'replace')
    at At.db (/opt/vnstat-client/resources/app.asar/app/background.js:1:52509)
    at Object.Month (/opt/vnstat-client/resources/app.asar/app/background.js:1:45322)
    at Object.getData (/opt/vnstat-client/resources/app.asar/app/background.js:1:45140)
    at IpcMainImpl.<anonymous> (/opt/vnstat-client/resources/app.asar/app/background.js:1:57500)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
16:57:40.454 › TypeError: Cannot read properties of undefined (reading 'replace')
    at At.db (/opt/vnstat-client/resources/app.asar/app/background.js:1:52509)
    at Object.Month (/opt/vnstat-client/resources/app.asar/app/background.js:1:45322)
    at Object.getData (/opt/vnstat-client/resources/app.asar/app/background.js:1:45140)
    at IpcMainImpl.<anonymous> (/opt/vnstat-client/resources/app.asar/app/background.js:1:57500)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
16:57:40.466 › TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.db (/opt/vnstat-client/resources/app.asar/app/background.js:1:52509)
    at Object.interfaces (/opt/vnstat-client/resources/app.asar/app/background.js:1:52824)
    at IpcMainImpl.<anonymous> (/opt/vnstat-client/resources/app.asar/app/background.js:1:57708)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)
16:57:40.467 › TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.db (/opt/vnstat-client/resources/app.asar/app/background.js:1:52509)
    at IpcMainImpl.<anonymous> (/opt/vnstat-client/resources/app.asar/app/background.js:1:57900)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:165:9959)
    at Object.emit (node:events:394:28)

```

**Expected behavior**
show data

**Screenshots**
![Screenshot from 2022-02-26 16-58-58](https://user-images.githubusercontent.com/48116123/155847759-8fd04ec9-2360-4be7-9668-c0fea7afc053.png)

**Desktop (please complete the following information):**
 - OS: manjaro
 - Browser  electron
 - Version v16.0.8

**Comment by Hulxv** [comment]
Please check #6 .

### Solution:
Go to ```/etc/vnstat.conf```
And remove semicolon before ```DatabaseDir```

**Comment by AliBasicCoder** [comment]
> Please check #6 .
> 
> ### Solution:
> Go to `/etc/vnstat.conf`, and remove semicolon before `DatabaseDir`

thanks, it's fixed now
